Homework1.1
mattmoana/example-master1 pull request #2
Opened 2022-11-20 15:26 UTC by mattmoana

2022-11-23 02:13 UTC, AntonBalakirev commented on src/com/company/Main.java
> +        System.out.println("Integer min value is: " + min);
можно сократить запись, не выделяя отдельную переменную

2022-11-23 02:20 UTC, AntonBalakirev requested changes

2022-11-23 02:20 UTC, AntonBalakirev commented on src/com/company/Main.java
> +        int max = Integer.MIN_VALUE;
значения перепутаны местами

2022-11-23 02:20 UTC, AntonBalakirev commented on src/com/company/Main.java
> +        //1.4 Напишите метод, который будет вычислять площадь прямоугольника и выводить результат в консоль, вызовите этот из main
Хорошим тоном было бы также выводить в консоль текст самого задания, чтобы сторонний пользователь понимал, что нужно делать

2022-11-23 02:20 UTC, AntonBalakirev commented on src/com/company/Main.java
> +        //1.4 Напишите метод, который будет вычислять площадь прямоугольника и выводить результат в консоль, вызовите этот из main
Хотелось бы увидеть отдельный метод для рассчета площади, который будет вызываться в основном методе main

2022-12-01 08:12 UTC, mattmoana commented on src/com/company/Main.java
> +        System.out.println("Integer min value is: " + min);
done

2022-12-01 08:13 UTC, mattmoana commented on src/com/company/Main.java
> +        int max = Integer.MIN_VALUE;
done

2022-12-01 08:15 UTC, mattmoana commented on src/com/company/Main.java
> +        //1.4 Напишите метод, который будет вычислять площадь прямоугольника и выводить результат в консоль, вызовите этот из main
done

2022-12-05 16:41 UTC, merged